name: build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: never
  CLICOLOR: 0
  NO_COLOR: "1"
  RUST_BACKTRACE: 1

permissions:
  contents: read
  checks: write

jobs:
  skip-check:
    runs-on: ubuntu-24.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5
        with:
          paths_ignore: '["**.md"]'
  checks:
    runs-on: ubuntu-latest
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true'
    steps:
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          persist-credentials: false

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2

      - name: Cargo fmt
        run: cargo fmt --check

      - name: Build
        run: cargo build

      - name: Clippy
        uses: auguwu/clippy-action@94a9ff2f6920180b89e5c03d121d0af04a9d3e03 # 1.4.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Spell Check Repo
        uses: crate-ci/typos@2d0ce569feab1f8752f1dde43cc2f2aa53236e06 # v1.40.0
  test:
    runs-on: ${{ matrix.os }}
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true'
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            runtime: docker
          - os: ubuntu-latest
            runtime: podman
          - os: macos-15
            runtime: podman
    env:
      SNOUTY_TEST_RUNTIME: ${{ matrix.runtime }}
    steps:
      - uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9 # v1
        with:
          toolchain: stable

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          persist-credentials: false

      - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2

      - name: Install Nextest
        uses: taiki-e/install-action@cargo-nextest

      # Actions has both Docker and Podman installed by default. We only want
      # to test with either.
      #
      # Additionally, podman compose falls back to docker-compose if it is
      # installed.
      #
      # Finally, current ubuntu-latest (24.04LTS) doesn't have new enough
      # podman-compose.
      - name: Configure Docker (Ubuntu)
        if: matrix.runtime == 'docker' && startsWith(matrix.os, 'ubuntu')
        run: |
          sudo rm -v -f "$(which podman)" "$(which podman-compose)"

      - name: Configure Podman (Ubuntu)
        if: matrix.runtime == 'podman' && startsWith(matrix.os, 'ubuntu')
        run: |
          sudo pip install podman-compose==1.1.0
          sudo rm -v -f "$(which docker)" /usr/libexec/docker/cli-plugins/docker-compose

      - name: Install Podman (macOS)
        if: matrix.runtime == 'podman' && startsWith(matrix.os, 'macos')
        run: |
          brew install podman podman-compose
          podman machine init
          podman machine start

      - name: Runtime Info
        shell: bash
        run: |
          if [ "${{ matrix.runtime }}" = "docker" ]; then
            docker info
          else
            podman info
          fi

      - name: Test
        run: cargo nextest run
  build-nix:
    runs-on: ubuntu-latest
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true'
    steps:
      - uses: samueldr/lix-gha-installer-action@7b7f14d320d6aacfb65bd1ef761566b3b69e474c # v2026-02-22

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          persist-credentials: false

      - name: Start Podman socket
        run: |
          systemctl --user start podman.socket

      - name: Test
        run: nix-shell --run "cargo nextest run"
